import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/common/AppSidebar";
import Header from "@/components/common/Header";
import {Inter} from 'next/font/google'
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"], weight:['200', '400', '600'] }); // Configurar la fuente
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}
      >
        <Toaster richColors/>
        <SidebarProvider defaultOpen={true}>
          <AppSidebar/>
          <main className="p-3 md:p-5 xl:px-10 w-full max-w-svw bg-secondary">
            <Header/>           
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
