import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/common/AppSidebar";
import Header from "@/components/common/Header";
import {Inter} from 'next/font/google'
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "@/providers/UserProvider";
import { cookies } from "next/headers";
import { getUserFromToken } from "@/app/auth/utils/auth";

const inter = Inter({ subsets: ["latin"], weight:['200', '400', '600'] }); 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  const cookieStore = await cookies()
  const token = cookieStore.get('authToken')?.value
  const initialUser = token ? await getUserFromToken(token):null

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster richColors />
        <Providers initialUser={initialUser}>
          {initialUser ? (
            <SidebarProvider defaultOpen={false}>
              <AppSidebar />
              <main className="p-3 md:p-5 xl:px-10 w-full max-w-svw bg-secondary">
                <Header />
                {children}
              </main>
            </SidebarProvider>
          ) : (
            <main className="w-full h-screen">
              {children}
            </main>
          )}
        </Providers>
      </body>
    </html>
  );
}
